import Head from 'next/head'

export default function Home() {
  console.log("hello")
  return (
    <>
      <Head>
        <title>New App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />              
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' text-4xl text-slate-600 flex items-center flex-col gap-4 px-8 justify-center h-screen '>
        <p>Time to cook</p>
        <p className='text-lg text-purple-900'>first time trying nextjs api route system, lets build some api</p>
        <p>stuff is hard, but lets cook</p>
      </main>
    </>
  )
}